---
# tasks file for roles/ubuntu/lamp
- name: Installing Apache HTTP Server
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Apache host index
  copy:
    content: "Midterm Exam - SANTOS, Jeanne Margarette"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index

- name: Starting the Apache Service
  service:
    name: apache2
    state: started
    enabled: yes
  when: apache_index.changed

- name: Whitelist Apache to ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Installing mysql
  apt:
    name: mysql-server
    state: present

- name: Installing PIP
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Installing the Pre-requisites
  apt:
    name: mariadb-server-10.3
    state: present
